### PR TITLE
Minor cleanups.

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Comment by roberthbailey** [comment]
You don't have any build instructions in your README (and I didn't try too hard to figure it out) so while this shouldn't break anything, you might test it once before merging.

**Comment by kelseyhightower** [comment]
Woot!

**Comment by roberthbailey** [comment]
Did you mean to close or merge?

**Comment by kelseyhightower** [comment]
@roberthbailey Merged!

**Comment by roberthbailey** [comment]
Thanks!

**Pull request merged**
